#!/usr/bin/env python3
"""Emit tab-drainage-credibility.tex (Peace two-way drainage-area alignment).

Presents NHD reference vs USGS NWIS site area, and the joint NHD-USGS / SWAT-NHD
agreement cross-tab. Source: stationAssignmentPageCatalog.json (peace).
"""
import json
import os

ROOT = "/data/SWATGenXApp/codes"
SRC = os.path.join(ROOT, "web_application/frontend/src/data/stationAssignmentPageCatalog.json")
OUT = os.path.join(ROOT, "publication/tables/generated/tab-drainage-credibility.tex")


def main():
    p = json.load(open(SRC))["peace"]
    dc = p["drainageCredibility"]; mo = p["mismatchOverlap"]; mx = mo["matrixAll"]
    n_site = dc["nWithNwisSiteDa"]; n_no = mo["nNoUsgsSiteDa"]
    med = dc["medianNhdOverNwis"]
    L = [
        "% Generated by publication/analysis/scripts/emit_tab_drainage_credibility_tex.py",
        f"% Source: {SRC}",
        r"\begin{tabular}{@{}lr@{}}",
        r"\toprule",
        r"Drainage-area alignment, Peace River & Count / ratio \\",
        r"\midrule",
        f"\\multicolumn{{2}}{{@{{}}l}}{{\\emph{{NHD reference vs USGS NWIS site area}} "
        f"(n={n_site} with site area; {n_no} lack it)}} \\\\",
        f"\\quad NHD within 10\\% of NWIS & {dc['nNhdWithin10pctOfNwis']} \\\\",
        f"\\quad NHD within 25\\% of NWIS & {dc['nNhdWithin25pctOfNwis']} \\\\",
        f"\\quad NHD $>$25\\% from NWIS & {dc['nNhdOver25pctFromNwis']} \\\\",
        f"\\quad Median NHD/NWIS ratio & {med:.2f} \\\\",
        r"\midrule",
        f"\\multicolumn{{2}}{{@{{}}l}}{{\\emph{{Joint NHD--USGS and SWAT--NHD agreement}} "
        f"(n={mx['n']})}} \\\\",
        f"\\quad Both agree ($|$NHD$-$USGS$|\\leq$25\\%, SWAT/NHD 0.5--2.0$\\times$) & {mx['bothOk']} \\\\",
        f"\\quad NHD--USGS mismatch only & {mx['onlyNhdUsgsMismatch']} \\\\",
        f"\\quad SWAT/NHD mismatch only & {mx['onlySwatNhdMismatch']} \\\\",
        f"\\quad Both mismatch & {mx['bothMismatch']} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"wrote {OUT}  (r_NHD-USGS_vs_SWAT-NHD = {mo['corrNhdNwisPctVsSwatNhdLogErr']:.3f})")


if __name__ == "__main__":
    main()
