#!/usr/bin/env python3
"""Emit LaTeX tabular for tab-controlled-gage-structure.csv (Objective 4 context table)."""
from __future__ import annotations

import csv
from pathlib import Path

from latex_emit_utils import latex_escape

REPO = Path(__file__).resolve().parents[3]
CSV_PATH = REPO / "publication/tables/tab-controlled-gage-structure.csv"
OUT = REPO / "publication/tables/generated/tab-controlled-gage-structure.tex"


def _cell(v: str) -> str:
    v = (v or "").strip()
    if not v or v.lower() == "not reported":
        return "---"
    if v.isdigit() or (v.replace(",", "").isdigit()):
        return f"{int(float(v)):,}".replace(",", "{,}")
    return latex_escape(v)


def main() -> None:
    rows = []
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row.get("status", "").startswith("frozen"):
                rows.append(row)
    lines = [
        "% Generated by publication/analysis/scripts/emit_tab_controlled_gage_structure_tex.py",
        r"\begin{tabular}{@{}llrrrrrrrrllr@{}}",
        r"\toprule",
        r"Basin ID & State & Ch. & Orig.\ cat. & Orig.\ reach & Div-2 & Isol.\ reach & Final ch. & Final sub. & Cal.\ period & Ver.\ period & HRUs \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            f"\\texttt{{{r['site_no']}}} & {r['state']} & {r['channel']} & "
            f"{_cell(r['orig_catchments'])} & {_cell(r['orig_reaches'])} & "
            f"{_cell(r['div2_removed'])} & {_cell(r['isolated_reaches_removed'])} & "
            f"{_cell(r['final_channels'])} & {_cell(r['final_subbasins'])} & "
            f"{latex_escape(r['calibration_period'])} & {latex_escape(r['verification_period'])} & "
            f"{_cell(r['n_hrus'])} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
