#!/usr/bin/env python3
"""Emit LaTeX table for Morris ensemble P-factor / R-factor metrics."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO_ROOT / "publication/tables/tab-sensitivity-ensemble-metrics.csv"
DEFAULT_OUT = REPO_ROOT / "publication/tables/generated/tab-sensitivity-ensemble-metrics.tex"


def _fmt(v: str, nd: int = 3) -> str:
    if not v or v.lower() in ("nan", "none", ""):
        return "---"
    return f"{float(v):.{nd}f}"


def emit(csv_path: Path, out_path: Path) -> None:
    rows = list(csv.DictReader(csv_path.open(newline="", encoding="utf-8")))
    if not rows:
        raise SystemExit("empty CSV")
    lines = [
        "% Generated by emit_tab_sensitivity_ensemble_metrics_tex.py",
        f"% Source: {csv_path.as_posix()}",
        r"\begin{tabular}{@{}llrrrr@{}}",
        r"\toprule",
        r"Basin & Step & $N$ & P-factor & R-factor & Best NSE \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            f"\\texttt{{{r['site_no']}}} & {r['frequency']} & {r['n_morris_members']} & "
            f"{_fmt(r['p_factor'])} & {_fmt(r['r_factor'])} & {_fmt(r['best_nse'])} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(rows)} rows)")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    emit(p.parse_args().csv, p.parse_args().out)


if __name__ == "__main__":
    main()
