#!/usr/bin/env python3
"""Emit tab-station-assignment.tex (Peace USGS station -> SWAT+ channel assignment).

Source of truth: web_application/frontend/src/data/stationAssignmentPageCatalog.json
(the up-to-date data behind the public USGS Station -> SWAT+ Assignment page).
"""
import json
import os

ROOT = "/data/SWATGenXApp/codes"
SRC = os.path.join(ROOT, "web_application/frontend/src/data/stationAssignmentPageCatalog.json")
OUT = os.path.join(ROOT, "publication/tables/generated/tab-station-assignment.tex")


def main():
    p = json.load(open(SRC))["peace"]
    ac = p["assignmentClass"]; mm = p["mappingMethod"]; fn = p["funnel"]
    n = fn["nStations"]
    L = [
        "% Generated by publication/analysis/scripts/emit_tab_station_assignment_tex.py",
        f"% Source: {SRC}",
        r"\begin{tabular}{@{}lr@{}}",
        r"\toprule",
        f"Peace River station assignment ({n} USGS gages) & Gages \\\\",
        r"\midrule",
        r"\multicolumn{2}{@{}l}{\emph{Assignment class}} \\",
        f"\\quad Clean tributary & {ac['tributary_clean']} \\\\",
        f"\\quad Mainstem, clean & {ac['mainstem_clean']} \\\\",
        f"\\quad Mainstem, known NHD offset & {ac['mainstem_known_nhd_offset']} \\\\",
        f"\\quad Lake-outlet review & {ac['lake_outlet_review']} \\\\",
        f"\\quad Canal/artificial review & {ac['canal_or_artificial_review']} \\\\",
        r"\midrule",
        r"\multicolumn{2}{@{}l}{\emph{Mapping method}} \\",
        f"\\quad Exact NHD$\\rightarrow$GIS crosswalk & {mm['exact_crosswalk']} \\\\",
        f"\\quad Lake-outlet replacement & {mm['lake_outlet_replacement']} \\\\",
        f"\\quad Controlled downstream replacement & {mm['downstream_replacement']} \\\\",
        r"\midrule",
        r"\multicolumn{2}{@{}l}{\emph{Calibration reconciliation funnel}} \\",
        f"\\quad Auto-calibration assignment class & {fn['nAssignmentCalReady']} \\\\",
        f"\\quad \\dots\\ with usable 2000--2024 daily flow ($\\geq$80\\%) & {fn['nObsUsableForCal']} \\\\",
        f"\\quad Fully calibration-ready & {fn['nCalReady']} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
