#!/usr/bin/env python3
"""Emit LaTeX tabular for tab-sensitivity-morris.csv (top parameters by mu*)."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO_ROOT / "publication/tables/tab-sensitivity-morris.csv"
DEFAULT_OUT = REPO_ROOT / "publication/tables/generated/tab-sensitivity-morris.tex"
TOP_N = 8


def _tex_param(name: str) -> str:
    return "\\texttt{" + name.replace("_", "\\_") + "}"


def emit(csv_path: Path, out_path: Path, top_n: int = TOP_N, site_no: str | None = None) -> None:
    with csv_path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    rows = [r for r in rows if r.get("status", "").startswith("frozen")]
    if site_no:
        rows = [r for r in rows if r.get("site_no") == site_no]
    rows.sort(key=lambda r: -float(r["mu_star"]))
    rows = rows[:top_n]
    if not rows:
        raise SystemExit(f"ERROR: no frozen Morris rows for site_no={site_no!r}")

    lines = [
        "% Generated by emit_tab_sensitivity_morris_tex.py",
        f"% Source: {csv_path.as_posix()}",
        f"% site_no: {site_no or 'all'}",
        r"\begin{tabular}{@{}rlrrr@{}}",
        r"\toprule",
        r"Rank & Parameter & $\mu$ & $\mu^*$ & $\sigma$ \\",
        r"\midrule",
    ]
    for i, r in enumerate(rows, start=1):
        lines.append(
            f"{i} & {_tex_param(r['parameter'])} & {float(r['mu']):.4f} & "
            f"{float(r['mu_star']):.4f} & {float(r['sigma']):.4f} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(rows)} rows)")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    p.add_argument("--top-n", type=int, default=TOP_N)
    p.add_argument("--site-no", type=str, default="", help="Filter to one USGS gage (e.g. 02297600)")
    p.add_argument(
        "--all-controlled-basins",
        action="store_true",
        help="Emit tab-sensitivity-morris-{site_no}.tex for each site in the CSV",
    )
    args = p.parse_args()
    if args.all_controlled_basins:
        with args.csv.open(newline="", encoding="utf-8") as f:
            sites = sorted({r["site_no"] for r in csv.DictReader(f) if r.get("site_no")})
        for site in sites:
            out = args.out.parent / f"tab-sensitivity-morris-{site}.tex"
            emit(args.csv, out, top_n=args.top_n, site_no=site)
        return
    emit(args.csv, args.out, top_n=args.top_n, site_no=args.site_no or None)


if __name__ == "__main__":
    main()
