#!/usr/bin/env python3
"""
Emit a LaTeX tabular fragment for locked rows in tab-model-complexity.csv.

Reads only rows with status=locked_from_inventory. Integer count columns are
copied verbatim from the CSV. Area (km$^2$) and DEM (m) are formatted to two
decimal places for the manuscript table; the CSV remains the canonical source.
Blank cells render as an em-dash placeholder (--- in LaTeX); blank lake counts
are not rewritten as ``0 or not present'' without a verified column in the CSV.

Output: publication/tables/generated/tab-model-complexity.tex (default).
The tables/generated/ tree is gitignored except .gitignore; run this script
before building the manuscript.

Usage (from repo root):
  python3 publication/analysis/scripts/emit_tab_model_complexity_tex.py
  python3 publication/analysis/scripts/emit_tab_model_complexity_tex.py --help
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _locked_basin_paths import DEFAULT_CSV, REPO_ROOT, load_locked_inventory_rows

DEFAULT_OUT = REPO_ROOT / "publication" / "tables" / "generated" / "tab-model-complexity.tex"
TIER_ORDER = {"S": 0, "M": 1, "L": 2, "Small": 0, "Medium": 1, "Large": 2}

# LaTeX: em dash for unavailable / blank CSV cells (not asserted as zero).
MISSING_TEX = r"{---}"


def _strip(v: str | None) -> str:
    return (v or "").strip()


def _cell_raw_or_dash(val: str | None) -> str:
    s = _strip(val)
    return s if s else MISSING_TEX


def _cell_lakes(val: str | None) -> str:
    """Blank n_lakes: not asserted as zero; render as missing."""
    return _cell_raw_or_dash(val)


def _cell_decimal2(val: str | None) -> str:
    """Format numeric area/DEM for manuscript display (two decimal places)."""
    s = _strip(val)
    if not s:
        return MISSING_TEX
    return f"{float(s):.2f}"


def _escape_tex(s: str) -> str:
    out: list[str] = []
    for ch in s:
        if ch in ("&", "%", "#", "_", "{", "}", "~", "^"):
            out.append("\\" + ch)
        elif ch == "\\":
            out.append("\\textbackslash{}")
        else:
            out.append(ch)
    return "".join(out)


def _model_id_tex(model_id: str) -> str:
    mid = _strip(model_id)
    return r"\texttt{\detokenize{" + mid + "}}"


def emit(csv_path: Path, out_path: Path) -> None:
    rows = load_locked_inventory_rows(csv_path)
    if not rows:
        raise SystemExit("ERROR: no locked_from_inventory rows in CSV")

    rows = sorted(
        rows,
        key=lambda r: TIER_ORDER.get(_strip(r.get("tier")), 99),
    )

    lines: list[str] = [
        "% Generated by publication/analysis/scripts/emit_tab_model_complexity_tex.py",
        "% Source: " + str(csv_path).replace("\\", "/"),
        "% Do not hand-edit; regenerate from CSV.",
        r"\begin{tabular}{@{}llllrrrrrrr@{}}",
        r"\toprule",
        r"Size class & Model ID & Basin & State & Area (km$^2$) & HRUs & Channels & Subbasins & Catchments & Lakes & DEM (m) \\",
        r"\midrule",
    ]

    for row in rows:
        tier = _escape_tex(_strip(row.get("tier")))
        label = _escape_tex(_strip(row.get("label")) or _strip(row.get("catalog_model_id")))
        state = _escape_tex(_strip(row.get("state")))
        area = _cell_decimal2(row.get("area_km2"))
        hrus = _cell_raw_or_dash(row.get("n_hrus"))
        ch = _cell_raw_or_dash(row.get("n_channels"))
        sub = _cell_raw_or_dash(row.get("n_subbasins"))
        catch = _cell_raw_or_dash(row.get("n_catchments"))
        lakes = _cell_lakes(row.get("n_lakes"))
        dem = _cell_decimal2(row.get("dem_resolution_m"))
        catalog = _strip(row.get("catalog_model_id")) or _strip(row.get("model_id"))
        mid = r"\texttt{" + _escape_tex(catalog) + "}"
        line = " & ".join([tier, mid, label, state, area, hrus, ch, sub, catch, lakes, dem]) + r" \\"
        lines.append(line)

    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV, help="Path to tab-model-complexity.csv")
    p.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Output .tex fragment (default: {DEFAULT_OUT})",
    )
    args = p.parse_args(argv)

    csv_path = args.csv.resolve()
    if not csv_path.is_file():
        print(f"ERROR: CSV not found: {csv_path}", file=sys.stderr)
        return 1

    out_path = args.out.resolve()
    emit(csv_path, out_path)
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
