#!/usr/bin/env python3
"""
Emit LaTeX longtable fragment for Supplementary Table S1 (reproducibility file manifest).

Usage (from repo root):
  python3 publication/analysis/scripts/emit_tab_repro_manifest_tex.py
"""
from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO_ROOT / "publication" / "supplement" / "tab-repro-file-manifest.csv"
DEFAULT_OUT = REPO_ROOT / "publication" / "tables" / "generated" / "tab-repro-file-manifest.tex"

# Fractions sum to 0.94\textwidth; colsep uses the remainder.
_COL_SPEC = (
    r"@{}"
    r">{\footnotesize\raggedright\arraybackslash}p{0.22\textwidth}"
    r">{\footnotesize\raggedright\arraybackslash}p{0.19\textwidth}"
    r">{\footnotesize\raggedright\arraybackslash}p{0.11\textwidth}"
    r">{\footnotesize\raggedright\arraybackslash}p{0.19\textwidth}"
    r">{\footnotesize\raggedright\arraybackslash}p{0.19\textwidth}"
    r"@{}"
)


def _tex_escape(s: str) -> str:
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
    )


def _break_camel(raw: str) -> str:
    out: list[str] = []
    prev = ""
    for ch in raw:
        if prev.islower() and ch.isupper():
            out.append("\x00")
        out.append(ch)
        prev = ch
    return "".join(out)


def _allow_breaks(raw: str) -> str:
    """Escape for LaTeX and insert optional line breaks in narrow table cells."""
    s = _break_camel(raw)
    s = _tex_escape(s)
    return (
        s.replace("\x00", "\\allowbreak ")
        .replace("/", "/\\allowbreak ")
        .replace("\\_", "\\_\\allowbreak ")
        .replace("; ", ";\\allowbreak ")
        .replace("-", "-\\allowbreak ")
    )


def _short_link(link: str, max_len: int = 44) -> str:
    l = link.strip()
    if len(l) <= max_len:
        return l
    return l[: max_len - 1].rstrip() + "…"


def _short_path(path: str, max_len: int = 42) -> str:
    p = path.strip()
    if len(p) <= max_len:
        return p
    parts = p.split("/")
    if len(parts) >= 2:
        tail = "/".join(parts[-2:])
        if len(tail) <= max_len:
            return f"…/{tail}"
    return "…" + p[-(max_len - 1) :]


def _short_notes(notes: str, max_len: int = 52) -> str:
    n = notes.strip()
    n = re.sub(r"https?://\\S+", "public benchmark page", n)
    n = re.sub(r"https?://\S+", "public benchmark page", n)
    if len(n) <= max_len:
        return n
    return n[: max_len - 1].rstrip() + "…"


def _short_generated(generated: str, max_len: int = 36) -> str:
    g = generated.strip()
    if ";" in g:
        parts = [_short_path(p.strip(), max_len=24) if "/" in p else p.strip() for p in g.split(";")]
        g = "; ".join(parts)
    elif "/" in g:
        g = _short_path(g, max_len=max_len)
    if len(g) <= max_len:
        return g
    return g[: max_len - 1].rstrip() + "…"


def _cell_file(path: str) -> str:
    return _allow_breaks(_short_path(path))


def _cell_generated(generated: str) -> str:
    return _allow_breaks(_short_generated(generated))


def emit(csv_path: Path, out_path: Path) -> None:
    with csv_path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        raise SystemExit(f"ERROR: no rows in {csv_path}")

    lines = [
        "% Generated by publication/analysis/scripts/emit_tab_repro_manifest_tex.py",
        f"% Source: {csv_path.as_posix()}",
        rf"\begin{{longtable}}{{{_COL_SPEC}}}",
        r"\caption{Reproducibility file manifest (Supplementary Table~S1). Repository-relative paths; "
        r"private host roots and credentials are excluded.} \label{tab:repro-file-manifest} \\",
        r"\toprule",
        r"File or folder & Purpose & Manuscript link & Generated by & Notes \\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{5}{l}{\textit{(continued from previous page)}} \\",
        r"\toprule",
        r"File or folder & Purpose & Manuscript link & Generated by & Notes \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{5}{r}{\textit{(continued on next page)}} \\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]

    for r in rows:
        file_or_folder = _cell_file(r["file_or_folder"])
        purpose = _allow_breaks(r["purpose"])
        link = _allow_breaks(_short_link(r["manuscript_link"]))
        generated = _cell_generated(r["generated_by"])
        notes = _allow_breaks(_short_notes(r["notes"]))
        lines.append(f"{file_or_folder} & {purpose} & {link} & {generated} & {notes} \\\\")

    lines.extend([r"\end{longtable}", ""])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(rows)} rows)")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()
    emit(args.csv, args.out)


if __name__ == "__main__":
    main()
