#!/usr/bin/env python3
"""
Emit a LaTeX tabular fragment for frozen rows in tab-metrics.csv.

Usage (from repo root):
  python3 publication/analysis/scripts/emit_tab_metrics_tex.py
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO_ROOT / "publication" / "tables" / "tab-metrics.csv"
DEFAULT_OUT = REPO_ROOT / "publication" / "tables" / "generated" / "tab-metrics.tex"

STAGE_ORDER = {
    "initialization_pool_best": 0,
    "calibration_global_best": 1,
    "verification_global_best": 2,
}
STEP_ORDER = {"Daily": 0, "Monthly": 1}

STATE_BY_SITE = {
    "02297600": "FL",
    "05536265": "IL",
}


def _strip(v: str | None) -> str:
    return (v or "").strip()


def _site_id_tex(site_no: str) -> str:
    return r"\texttt{" + site_no + "}"


def emit(csv_path: Path, out_path: Path) -> None:
    with csv_path.open(newline="", encoding="utf-8") as f:
        rows = [r for r in csv.DictReader(f) if _strip(r.get("status", "")).startswith("frozen")]

    if not rows:
        raise SystemExit("ERROR: no frozen rows in tab-metrics.csv")

    rows.sort(
        key=lambda r: (
            _strip(r.get("site_no")),
            STAGE_ORDER.get(_strip(r.get("workflow_stage")), 99),
            STEP_ORDER.get(_strip(r.get("time_step")), 99),
        )
    )

    stage_label = {
        "initialization_pool_best": "Init.\\ pool best",
        "calibration_global_best": "Calibration best",
        "verification_global_best": "Verification best",
    }

    lines = [
        "% Generated by publication/analysis/scripts/emit_tab_metrics_tex.py",
        f"% Source: {csv_path.as_posix()}",
        r"\begin{tabular}{@{}lllllllrrrrr@{}}",
        r"\toprule",
        r"Basin ID & State & Channel & Stage & Period & Step & NSE & KGE & PBIAS (\%) & RMSE (cfs) & MAPE (\%) \\",
        r"\midrule",
    ]

    for r in rows:
        site = _strip(r["site_no"])
        state = _strip(r.get("state")) or STATE_BY_SITE.get(site, "---")
        channel = _strip(r.get("station_id"))
        stage = stage_label.get(_strip(r["workflow_stage"]), _strip(r["workflow_stage"]))
        period = _strip(r["scored_period"]).replace(" to ", "--")
        step = _strip(r["time_step"])
        lines.append(
            f"{_site_id_tex(site)} & {state} & {channel} & {stage} & {period} & {step} & "
            f"{_strip(r['nse'])} & {_strip(r['kge'])} & {_strip(r['pbias_pct'])} & "
            f"{_strip(r['rmse'])} & {_strip(r['mpe_pct'])} \\\\"
        )

    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(rows)} rows)")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()
    emit(args.csv, args.out)


if __name__ == "__main__":
    main()
