#!/usr/bin/env python3
"""Emit LaTeX tabular for tab-nhd-preprocessing-qa.csv (S/M/L manuscript table)."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO / "publication/tables/tab-nhd-preprocessing-qa.csv"
DEFAULT_OUT = REPO / "publication/tables/generated/tab-nhd-preprocessing-qa-sm-l.tex"
TIER_ORDER = {"S": 0, "M": 1, "L": 2, "X20": 3, "X40": 4, "X60": 5}


def _cell(v: str) -> str:
    v = (v or "").strip()
    return "---" if not v else f"{int(float(v)):,}".replace(",", "{,}")


def _emit_rows(rows: list[dict], out_path: Path) -> None:
    lines = [
        "% Generated by publication/analysis/scripts/emit_tab_nhd_preprocessing_qa_tex.py",
        f"% Source: {DEFAULT_CSV.as_posix()}",
        r"\begin{tabular}{@{}llrrrrrrrrrr@{}}",
        r"\toprule",
        r"Size class & Model & Orig. cat. & Orig. reach & Div-2 & Isol. reach & Isol. cat. & Orphan cat. & No-VAA & Final ch. & Final sub. & Final ws. \\",
        r"\midrule",
    ]
    for r in rows:
        tier = r.get("tier") or r.get("cohort", "")
        lines.append(
            f"{tier} & \\texttt{{{r['catalog_model_id']}}} & "
            f"{_cell(r.get('original_catchments', ''))} & "
            f"{_cell(r.get('input_reaches', ''))} & "
            f"{_cell(r['divergence2_removed'])} & "
            f"{_cell(r.get('isolated_reaches_removed', ''))} & "
            f"{_cell(r.get('isolated_catchments_merged', ''))} & "
            f"{_cell(r.get('orphan_catchments_merged', ''))} & "
            f"{_cell(r['no_vaa_catchments_dissolved'])} & "
            f"{_cell(r['final_channels'])} & "
            f"{_cell(r['final_subbasins'])} & "
            f"{_cell(r.get('final_watersheds', ''))} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(rows)} rows)")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()

    with args.csv.open(newline="", encoding="utf-8") as f:
        rows = [r for r in csv.DictReader(f) if r.get("status", "").startswith("frozen")]

    sml = [r for r in rows if r.get("tier") in ("S", "M", "L")]
    sml.sort(key=lambda r: TIER_ORDER[r["tier"]])
    _emit_rows(sml, args.out)


if __name__ == "__main__":
    main()
