#!/usr/bin/env python3
"""
Emit LaTeX tabularx fragment for tab-tool-contrast.csv (documented_qualitative rows).

Column types Z and Y are defined in publication/manuscript/main.tex (ragged2e + tabularx).

Usage (from repo root):
  python3 publication/analysis/scripts/emit_tab_tool_contrast_tex.py
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO_ROOT / "publication" / "tables" / "tab-tool-contrast.csv"
DEFAULT_OUT = REPO_ROOT / "publication" / "tables" / "generated" / "tab-tool-contrast.tex"

COLUMNS = [
    ("system", "System"),
    ("delivery_mode", "Delivery"),
    ("swat_family_engine", "SWAT engine"),
    ("hydrography_backbone", "Hydrography"),
    ("hydrography_preprocessing", "Preprocessing / aggregation"),
    ("simulation_platform_outputs", "Simulation \\& outputs"),
]

ROW_KEYS = [key for key, _ in COLUMNS]


def _strip(v: str | None) -> str:
    return (v or "").strip()


def _escape_tex(s: str) -> str:
    out: list[str] = []
    for ch in s:
        if ch in ("&", "%", "#", "_", "{", "}", "~", "^"):
            out.append("\\" + ch)
        elif ch == "\\":
            out.append("\\textbackslash{}")
        else:
            out.append(ch)
    return "".join(out)


def _cell(raw: str) -> str:
    return _escape_tex(_strip(raw))


def emit(csv_path: Path, out_path: Path) -> None:
    with csv_path.open(newline="", encoding="utf-8") as f:
        rows = [r for r in csv.DictReader(f) if _strip(r.get("status")) == "documented_qualitative"]

    if not rows:
        raise SystemExit("ERROR: no documented_qualitative rows in tab-tool-contrast.csv")

    header = " & ".join(h for _, h in COLUMNS) + r" \\"
    lines = [
        "% Generated by publication/analysis/scripts/emit_tab_tool_contrast_tex.py",
        f"% Source: {csv_path.as_posix()}",
        r"\begin{tabularx}{\textwidth}{@{} Z Y Y Y Y Y @{}}",
        r"\toprule",
        header,
        r"\midrule",
    ]
    for row in rows:
        cells = [_cell(row[key]) for key in ROW_KEYS]
        lines.append(" & ".join(cells) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabularx}", ""])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(rows)} rows)")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()
    emit(args.csv.resolve(), args.out.resolve())


if __name__ == "__main__":
    main()
