#!/usr/bin/env python3
"""
Emit a LaTeX tabular fragment for documented generation-time rows in tab-runtime.csv.

Joins HRU counts from tab-model-complexity.csv (locked_from_inventory) by catalog_model_id.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

from _locked_basin_paths import DEFAULT_CSV as COMPLEXITY_CSV, load_locked_inventory_rows

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO_ROOT / "publication" / "tables" / "tab-runtime.csv"
DEFAULT_OUT = REPO_ROOT / "publication" / "tables" / "generated" / "tab-runtime.tex"

TIER_ORDER = {"S": 0, "M": 1, "L": 2}
MISSING_TEX = r"{---}"


def _strip(v: str | None) -> str:
    return (v or "").strip()


def _catalog_id_tex(catalog_id: str) -> str:
    return r"\texttt{" + _strip(catalog_id) + "}"


def _minute_cell(val: str | None) -> str:
    s = _strip(val)
    if not s:
        return MISSING_TEX
    return f"{float(s):.1f}"


def _load_hrus_by_catalog_id(complexity_csv: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for row in load_locked_inventory_rows(complexity_csv):
        cid = _strip(row.get("catalog_model_id"))
        if cid:
            out[cid] = _strip(row.get("n_hrus")) or MISSING_TEX
    return out


def emit(runtime_csv: Path, complexity_csv: Path, out_path: Path) -> None:
    hrus = _load_hrus_by_catalog_id(complexity_csv)

    with runtime_csv.open(newline="", encoding="utf-8") as f:
        rows = [
            r for r in csv.DictReader(f)
            if _strip(r.get("status")) in {
                "measured_scripted_rerun",
                "measured_celery_job",
                "measured_qswat_assembly_max",
                "documented_estimate",
            }
        ]

    if not rows:
        raise SystemExit("ERROR: no documented runtime rows in tab-runtime.csv")

    rows.sort(key=lambda r: TIER_ORDER.get(_strip(r.get("tier")), 99))

    lines = [
        "% Generated by publication/analysis/scripts/emit_tab_runtime_tex.py",
        f"% Runtime source: {runtime_csv.as_posix()}",
        f"% HRUs joined from: {complexity_csv.as_posix()}",
        r"\begin{tabular}{@{}lllrrrr@{}}",
        r"\toprule",
        r"Tier & Model ID & Basin & HRUs & Wall time (min) & vCPU & Workers \\",
        r"\midrule",
    ]

    for row in rows:
        tier = _strip(row.get("tier"))
        cid = _strip(row.get("catalog_model_id"))
        label = _strip(row.get("label"))
        wall = _minute_cell(row.get("fresh_rerun_wall_min"))
        cpu = _strip(row.get("cpu_count")) or MISSING_TEX
        workers = _strip(row.get("worker_count")) or MISSING_TEX
        hru = hrus.get(cid, MISSING_TEX)
        line = " & ".join([tier, _catalog_id_tex(cid), label, hru, wall, cpu, workers]) + r" \\"
        lines.append(line)

    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(rows)} rows)")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    p.add_argument("--complexity-csv", type=Path, default=COMPLEXITY_CSV)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()
    emit(args.csv.resolve(), args.complexity_csv.resolve(), args.out.resolve())


if __name__ == "__main__":
    main()
