#!/usr/bin/env python3
"""Emit tab-drainage-area-pipeline-trace.tex from the Peace phase-3 pipeline trace.

Median SWAT+/NHD ratio per stage is computed across the mainstem diagnostic-panel
gages in publication/analysis/qa/peace-drainage-area-pipeline-trace.csv (stage H is
pending a Peace shape restore; see peace-drainage-area-audit-findings.md).
"""
import csv
import os
import statistics as st

ROOT = "/data/SWATGenXApp/codes"
SRC = os.path.join(ROOT, "publication/analysis/qa/peace-drainage-area-pipeline-trace.csv")
SRC_3B = os.path.join(ROOT, "publication/analysis/qa/peace-drainage-area-pipeline-3b-trace.csv")
OUT = os.path.join(ROOT, "publication/tables/generated/tab-drainage-area-pipeline-trace.tex")

# stage code -> (csv column, quantity label, interpretation)
STAGES = [
    ("A", "stage_a_nhd_totdasqkm_zip",
     r"Original NHDPlus HR HU4 \texttt{TotDASqKm} (VAA)",
     r"Reference cumulative drainage at the gaged reach"),
    ("B", "stage_b_nhd_orig_upstream_areasqkm_zip",
     r"Original upstream $\Sigma$ \texttt{AreaSqKm} (HU4 network)",
     r"Independent cumulative cross-check; agrees with A"),
    ("G", "stage_g_streams_pkl_reach_totdasqkm",
     r"Cleaned flowline reach \texttt{TotDASqKm}",
     r"Pre-QSWAT\textsuperscript{+} attribute; $<$0.1\% vs A (VAA not pre-inflated)"),
    ("C", "stage_c_clean_streams_upstream_areasqkm_km2",
     r"Cleaned flowline-network upstream $\Sigma$",
     r"After topology cleaning; no positive bias"),
    ("D", "stage_d_swatgenx_postprocessed_polygon_upstream_km2",
     r"Post-processed watershed-polygon upstream $\Sigma$",
     r"SWATGenX subbasin polygons; $+2$--$3\%$ only"),
    ("E", "stage_e_qswat_areac_at_assignment_km2",
     r"QSWAT\textsuperscript{+}/TauDEM channel \texttt{AreaC} at assignment",
     r"First large exceedance ($+15$--$17\%$)"),
    ("F", "stage_f_chandeg_km2",
     r"\texttt{chandeg.con} executable area",
     r"Headline audit column; matches E"),
]


def main():
    rows = [r for r in csv.DictReader(open(SRC)) if r["panel_role"].startswith("mainstem")]

    def med_ratio(col):
        vals = []
        for r in rows:
            try:
                a = float(r["stage_a_nhd_totdasqkm_zip"]); v = float(r[col])
                if a > 0 and v > 0:
                    vals.append(v / a)
            except (ValueError, KeyError):
                pass
        return st.median(vals) if vals else None

    out = [
        "% Generated by publication/analysis/scripts/emit_tab_drainage_area_pipeline_trace_tex.py",
        f"% Source: {SRC} (mainstem diagnostic-panel gages; n={len(rows)})",
        r"\begin{tabular}{@{}clcp{5.0cm}@{}}",
        r"\toprule",
        r"Stage & Quantity & Median ratio vs NHD \texttt{TotDASqKm} & Interpretation \\",
        r"\midrule",
    ]
    for code, col, label, interp in STAGES:
        r = med_ratio(col)
        out.append(f"{code} & {label} & {r:.2f} & {interp} \\\\")

    # Stage H from phase-3b trace (live project channel area): mainstem median rivs1/A.
    h_ratio = None
    if os.path.exists(SRC_3B):
        h_vals = []
        for r in csv.DictReader(open(SRC_3B)):
            if not r["panel_role"].startswith("mainstem"):
                continue
            try:
                a = float(r["stage_a_nhd_totdasqkm_zip"]); h = float(r["stage_h_rivs1_areac_km2"])
                if a > 0 and h > 0:
                    h_vals.append(h / a)
            except (ValueError, KeyError):
                pass
        if h_vals:
            h_ratio = st.median(h_vals)
    if h_ratio is not None:
        out.append(
            f"H & Live \\texttt{{rivs1.AreaC}} / project SQLite & {h_ratio:.2f} & "
            r"Matches E/F ($<$0.1\% vs \texttt{chandeg}); offset present before export \\")
    else:
        out.append(
            r"H & Live \texttt{rivs1.AreaC} / project SQLite & --- & "
            r"Pending (Peace \texttt{Watershed/Shapes} not on disk) \\")
    out += [
        r"\bottomrule",
        r"\end{tabular}",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT} (mainstem n={len(rows)})")


if __name__ == "__main__":
    main()
