#!/usr/bin/env python3
"""Emit tab-drainage-area-audit.tex from the published drainage-area audit catalog.

Source of truth: web_application/frontend/src/data/drainageAreaAuditCatalog.json
(the up-to-date data behind the public SWAT+ Drainage Area Audit page).
"""
import json
import os

ROOT = "/data/SWATGenXApp/codes"
SRC = os.path.join(ROOT, "web_application/frontend/src/data/drainageAreaAuditCatalog.json")
OUT = os.path.join(ROOT, "publication/tables/generated/tab-drainage-area-audit.tex")


def main():
    cat = json.load(open(SRC))
    rows = []
    tot_n = tot_match = tot_within = tot_out = 0
    for m in cat["models"]:
        s = m["summary"]
        tier = m.get("tier") or "Cal"
        med = s.get("medianSwatNhdRatio")
        med_s = f"{med:.2f}" if med is not None else "---"
        rows.append((tier, m["catalogModelId"], m.get("state", "---"),
                     s["nStations"], s["nMatchedSwatNhd"], med_s,
                     s["withinHalfToDouble"], s["nAssignmentOutliers"]))
        tot_n += s["nStations"]; tot_match += s["nMatchedSwatNhd"]
        tot_within += s["withinHalfToDouble"]; tot_out += s["nAssignmentOutliers"]

    lines = [
        "% Generated by publication/analysis/scripts/emit_tab_drainage_area_audit_tex.py",
        f"% Source: {SRC} (lastUpdated {cat.get('lastUpdated','?')})",
        r"\begin{tabular}{@{}lllrrrrr@{}}",
        r"\toprule",
        r"Tier & Catalog ID & State & Stations & Matched & Median SWAT/NHD & "
        r"Within 0.5--2.0$\times$ & Outliers \\",
        r"\midrule",
    ]
    for tier, mid, state, n, match, med_s, within, out in rows:
        lines.append(f"{tier} & \\texttt{{{mid}}} & {state} & {n} & {match} & "
                     f"{med_s} & {within} & {out} \\\\")
    lines += [
        r"\midrule",
        f"\\textbf{{All}} & --- & --- & \\textbf{{{tot_n}}} & \\textbf{{{tot_match}}} & "
        f"--- & \\textbf{{{tot_within}}} & \\textbf{{{tot_out}}} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(rows)} models; {tot_n} stations, {tot_within} within band)")


if __name__ == "__main__":
    main()
