#!/usr/bin/env python3
"""Turn the coupled-Morris results (morris_indices_<qoi>.csv) into the manuscript
SI figure (mu*-sigma scatter, one panel per QoI) and a LaTeX ranking table.

  python make_morris_figure.py [RESULTS_DIR]
Writes: paper/figures/si_morris.png  and  paper/sections/si_morris_table.tex
"""
import os, sys, csv
import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
RES = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "results")
PAPER = os.path.normpath(os.path.join(HERE, "..", "paper"))
FIGOUT = os.path.join(PAPER, "figures", "si_morris.png")
TEXOUT = os.path.join(PAPER, "sections", "si_morris_table.tex")

QOIS = [("instream_lower", "In-stream PFOS, lower mainstem (RR-0020)", "In-stream (low)"),
        ("instream_mid",   "In-stream PFOS, mid mainstem (RR-0050)",   "In-stream (mid)"),
        ("gw_plume",        "Groundwater plume concentration",          "GW plume"),
        ("baseflow",        "Net groundwater baseflow",                 "Baseflow")]
# leg colour by parameter
LEG = {p: c for c, ps in {
    "tab:orange": ["soil_scale", "koc_scale", "kl", "lm", "percop"],
    "tab:blue":   ["kh", "kv", "rch", "ghb", "drn", "pump", "sfrk"],
    "tab:green":  ["t_kf", "t_n", "t_alh", "t_ath", "t_cap", "t_bg"],
}.items() for p in ps}
LABEL = {"soil_scale": "soil load", "koc_scale": "$K_{oc}$", "kl": "Langmuir $k_L$",
         "lm": "Langmuir $\\Gamma_{max}$", "percop": "perc. partition",
         "kh": "$K_h$", "kv": "$K_v$", "rch": "recharge", "ghb": "GHB cond.",
         "drn": "drain cond.", "pump": "pumping", "sfrk": "SFR-bed $K$",
         "t_kf": "aq. $K_f$", "t_n": "aq. $n$", "t_alh": "$\\alpha_L$",
         "t_ath": "$\\alpha_T$", "t_cap": "source", "t_bg": "background"}

def load(qoi):
    p = os.path.join(RES, f"morris_indices_{qoi}.csv")
    if not os.path.exists(p): return None
    rows = list(csv.DictReader(open(p)))
    return [(r["param"], float(r["mu_star"]), float(r["mu_star_conf"]), float(r["sigma"])) for r in rows]

def main():
    data = {q: load(q) for q, _, _ in QOIS}
    avail = [(q, t, sh) for q, t, sh in QOIS if data[q]]
    if not avail:
        print("no morris_indices_*.csv found in", RES); sys.exit(1)

    # ---- figure: mu*-sigma scatter, one panel per QoI ----
    n = len(avail); ncol = 2; nrow = (n + 1) // 2
    fig, axs = plt.subplots(nrow, ncol, figsize=(11, 4.2 * nrow))
    axs = np.atleast_1d(axs).ravel()
    for ax, (q, title, _sh) in zip(axs, avail):
        rows = data[q]
        ms = np.array([r[1] for r in rows]); sg = np.array([r[3] for r in rows])
        mx = max(ms.max(), 1e-9)
        for nm, m, mc, s in rows:
            ax.errorbar(m, s, xerr=mc, fmt="o", ms=7, color=LEG.get(nm, "gray"),
                        ecolor="lightgray", capsize=2, zorder=3)
            if m > 0.06 * mx or s > 0.06 * max(sg.max(), 1e-9):
                ax.annotate(LABEL.get(nm, nm), (m, s), fontsize=7.5,
                            xytext=(4, 3), textcoords="offset points")
        lim = mx * 1.15
        ax.plot([0, lim], [0, lim], "k:", lw=0.8, alpha=0.6)       # sigma = mu*
        ax.plot([0, lim], [0, 0.5 * lim], "k--", lw=0.6, alpha=0.4)  # sigma = 0.5 mu*
        ax.set_xlabel("$\\mu^*$ (mean |elementary effect|)"); ax.set_ylabel("$\\sigma$")
        ax.set_title(title, fontsize=9.5); ax.set_xlim(left=-0.02 * lim); ax.set_ylim(bottom=-0.02 * lim)
        ax.grid(alpha=0.25)
    for ax in axs[len(avail):]:
        ax.axis("off")
    from matplotlib.lines import Line2D
    handles = [Line2D([], [], marker="o", ls="", color=c, label=l) for c, l in
               [("tab:orange", "surface-water PFAS"), ("tab:blue", "groundwater flow"),
                ("tab:green", "groundwater transport")]]
    fig.legend(handles=handles, loc="lower center", ncol=3, fontsize=9, frameon=False,
               bbox_to_anchor=(0.5, -0.01))
    fig.tight_layout(rect=[0, 0.03, 1, 1])
    os.makedirs(os.path.dirname(FIGOUT), exist_ok=True)
    fig.savefig(FIGOUT, dpi=150, bbox_inches="tight")
    print("wrote", FIGOUT)

    # ---- LaTeX table: mu* ranking per QoI (top params) ----
    # union of top-6 params across QoIs, ordered by max mu* share
    order, seen = [], set()
    for q, *_ in avail:
        for nm, m, mc, s in sorted(data[q], key=lambda r: -r[1])[:6]:
            if nm not in seen: seen.add(nm); order.append(nm)
    # normalise mu* to % of the per-QoI max for comparability
    norm = {}
    for q, *_ in avail:
        mx = max(r[1] for r in data[q]) or 1.0
        norm[q] = {r[0]: 100 * r[1] / mx for r in data[q]}
    legname = {"tab:orange": "SW", "tab:blue": "GWf", "tab:green": "GWt"}
    with open(TEXOUT, "w") as f:
        f.write("% auto-generated by sa/make_morris_figure.py\n")
        f.write("\\begin{table}[t]\\centering\\footnotesize\n")
        f.write("\\caption{Coupled Morris elementary-effects screening: relative parameter "
                "importance ($\\mu^*$ as \\% of the most influential parameter for each "
                "quantity of interest). Shown are the union of the six most influential "
                "parameters per quantity of interest (13 of the 18 screened parameters; the "
                "remaining five rank outside the top six for every quantity of interest). "
                "Leg: SW = surface-water PFAS, GWf = groundwater flow, "
                "GWt = groundwater transport.}\n\\label{tab:morris}\n")
        f.write("\\begin{tabular}{@{}ll" + "r" * len(avail) + "@{}}\n\\toprule\n")
        f.write("Parameter & Leg & " + " & ".join(sh for _q,_t,sh in avail) + " \\\\\n\\midrule\n")
        for nm in order:
            leg = legname.get(LEG.get(nm, ""), "")
            cells = " & ".join(f"{norm[q].get(nm, 0):.0f}" for q, *_ in avail)
            f.write(f"{LABEL.get(nm, nm)} & {leg} & {cells} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    print("wrote", TEXOUT)

if __name__ == "__main__":
    main()
